config/routes.rb
Rails.application.routes.draw do
  get 'availabilities/show', as: :show_availabilities

  get 'availabilities/update', as: :update_availabilities

  resources :participatings
  post "participatings/create_or_update" => 'participatings#create_or_update', as: :participating_create_or_update

  resources :leaders

  resources :announcements

  resources :character_specialisations

  resources :characters

  resources :pickups

  resources :requireds

  resources :roles

  resources :event_templates

  resources :events

  resources :role_types

  get 'guild/index'

  get 'guild/about', as: :about

  put 'guild/promote_user/:uid' => 'guild#promote_user' , as: :user_promote_admin
  put 'guild/demote_user/:uid'  => 'guild#demote_user', as: :user_demote_admin
  put 'guild/make_pickup/:uid' => 'guild#make_pickup', as: :user_make_pickup
  put 'guild/make_guildmate/:uid' => 'guild#make_guildmate', as: :user_make_guildmate

  delete 'guild/remove_user/:uid'  => 'guild#remove_user', as: :user_delete

  devise_for :users

  root 'guild#index'

end

app/controllers/guild_controller.rb
class GuildController < ApplicationController
  before_action :set_user, only: [:make_pickup, :make_guildmate, :promote_user, :demote_user, :remove_user]
  
  before_action :is_admin?, except: [:index]

  def index
  	@events = Event.recent
  	@announcements = Announcement.recent
  end

  def about
  	@users = User.all
  end

  def make_pickup 
    @users = User.all
    logger.info @user.inspect
    if @user.nil?
      render about_path, alert: "Utilisateur inconnu"
    else
      @user.pickups = true
      @user.save
      render about_path, notice: "Démotion effectuée"
    end
  end

  def make_guildmate
    @users = User.all
    if @user.nil?
      render about_path, alert: "Utilisateur inconnu"
    else
      @user.pickups = false
      @user.save
      render about_path, notice: "Promotion effectuée"
    end
  end

  def promote_user
    @users = User.all
  	if @user.nil?
  		render about_path, alert: "Utilisateur inconnu"
  	else
  		@user.is_admin = true
  		@user.save
  		render about_path, notice: "Promotion effectuée"
  	end
  end

  def demote_user
    @users = User.all
  	if @user.nil?
  		render about_path, alert: "Utilisateur inconnu"
  	else
  		@user.is_admin = false
  		@user.save
  		render about_path, notice: "Démotion effectuée"
  	end
  end

  def remove_user
    @users = User.all
  	if @user.nil?
  		render about_path, alert: "Utilisateur inconnu"
  	else
  		@user.destroy
  		render about_path, notice: "Utilisateur supprimer"
  	end
  end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      	@user = User.find(params[:uid])
    end
end

app/helpers/guild_helper.rb
module GuildHelper
end

app/views/guild/about.html.erb
<h2>Membres</h2>

<table class="table">
	<tr>
		<th>Username</th>
		<th>Email</th>
		<th>Actions</th>
	</tr>
	<% @users.each do |user| %>
	<tr>
		<td><%= user.username %></td>
		<td><%= user.email %></td>
		<td><%= link_to "Devien Pickup", user_make_pickup_path(user), method: :put, class: "btn btn-default btn-md" if not user.pickups and user != current_user %> 
			<%= link_to "Devien Guildé", user_make_guildmate_path(user), method: :put, class: "btn btn-default btn-md" if user.pickups and user != current_user%> 
			<%= link_to "Devien admin", user_promote_admin_path(user), method: :put, class: "btn btn-default btn-md" if not user.is_admin%> <%= link_to "Devien utilisateur", user_demote_admin_path(user) , method: :put, class: "btn btn-default btn-md" if user.is_admin and user != current_user %>&nbsp;<%= link_to "Supprimer", user_delete_path(user),method: :delete, data: { confirm: 'Etes vous sure ?' } , class: "btn btn-default btn-md"  if user != current_user  %> <%= "Ne peux rien faire sur soit même" if current_user == user %></td>
	</tr>
	<% end %>
</table>

app/views/guild/index.html.erb
 <div class="row">
 	
 	<div class="col-md-6">

		<div class="page-header ">
		  <h2><i class="fa fa-calendar"></i>&nbsp;&nbsp;Prochains Evènements</h2>
		</div>
		<%if user_signed_in? and current_user.characters.count == 0 %>
			<p class="alert alert-danger"><span style="background-color:darkred" title="Pas de personnages créé !" class="badge ">!</span>&nbsp;Vous devez avoir au moins un personnage pour pouvoir participer aux évènements !&nbsp;<a href="<%= new_character_path%>">&nbsp;Créez votre personnage</a>
	      	</p>
	    <%end%>
	    <% if user_signed_in? %>
		<a class="btn btn-default btn-md" href="<%= events_path %>"><i class="fa fa-edit"></i>&nbsp; Gérez vos disponibilités </a>
		<% end %>
		<br/><br/>

	       <% @events.each do |event| %>
		      <div class="panel panel-default">
		        <div class="event-header panel-heading clearfix">
		            <div class="pull-left">
		              <h3 class="panel-title"><%= link_to event.name, event %></h3>
		              <small><i class="glyphicon glyphicon-time"></i>&nbsp;<%= l event.start_time, :format => :short %></small>
		              <% if !event.subscription_opened? %> 
		              	<i class="fa fa-gavel color-darkred"></i> <small class="color-darkred"> Inscriptions fermées !</small>
		              <% end %>
		            </div>
		            <div class="pull-right text-right">
		              <span class="badge "><%= event.actual_players%>&nbsp;<i class="fa fa-user"></i></span> / <span class="badge "><%= event.players_required %>&nbsp;<i class="fa fa-users"></i></span><br/>
        				<span class="badge palier-<%= event.tier || 1 %>">
        					<i class="fa fa-bar-chart-o"></i>&nbsp;Palier <%= event.tier || 1 %>
        				</span>
		            </div>
		        </div>
		      </div>
	    	<% end %>
  	</div>

    <!-- Main Blog Content -->
    <div class="col-md-6">	 

		<div class="page-header">
		  <h2><i class="fa fa-bookmark"></i>&nbsp;&nbsp;Dernière Annonce !</h2>
		</div>
		<% @announcements.each do |an| %>
	      <article>
	 
	        <h3><%= link_to an.title, announcements_path(anchor: "announcement_#{an.id}") %></h3>
	        <h6>Auteur <%= an.user.username %> le <%= l an.created_at, format: :short %></h6>
	 
	            <%= markdown(truncate(an.content, length: 200)) %>
	 
	        <%= link_to "Suite...", announcements_path(anchor: "announcement_#{an.id}") %>
	 
	      </article>
	    <% end %>
	        <%= link_to "Voir les autres articles", announcements_path %>
    </div>
</div>	
 