config/routes.rb
Rails.application.routes.draw do
  get 'availabilities/show', as: :show_availabilities

  get 'availabilities/update', as: :update_availabilities

  resources :participatings
  post "participatings/create_or_update" => 'participatings#create_or_update', as: :participating_create_or_update

  resources :leaders

  resources :announcements

  resources :character_specialisations

  resources :characters

  resources :pickups

  resources :requireds

  resources :roles

  resources :event_templates

  resources :events

  resources :role_types

  get 'guild/index'

  get 'guild/about', as: :about

  put 'guild/promote_user/:uid' => 'guild#promote_user' , as: :user_promote_admin
  put 'guild/demote_user/:uid'  => 'guild#demote_user', as: :user_demote_admin
  put 'guild/make_pickup/:uid' => 'guild#make_pickup', as: :user_make_pickup
  put 'guild/make_guildmate/:uid' => 'guild#make_guildmate', as: :user_make_guildmate

  delete 'guild/remove_user/:uid'  => 'guild#remove_user', as: :user_delete

  devise_for :users

  root 'guild#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :roles, dependent: :destroy
	has_many :leaders, dependent: :destroy

	has_many :users, through: :leaders
	validates :leaders, presence: true

	scope :recent, -> { where("start_time > ?", (DateTime.now.utc + DateTime.now.utc_offset.seconds)).order(start_time: :asc) }
	scope :old, -> { where("start_time < ? AND start_time > ?",DateTime.now.utc + DateTime.now.utc_offset.seconds, 10.day.ago).order(start_time: :desc) }


	accepts_nested_attributes_for :users
	accepts_nested_attributes_for :roles, :reject_if => lambda { |a| a[:required_players].blank? || a[:role_type_id].blank?}

	def actual_players
		ct = 0
		roles.each do |r|
			ct += r.participating.where(available: true).count
		end
		ct
	end

	def subscription_opened? 
		DateTime.now.utc + DateTime.now.utc_offset.seconds  < (start_time - 15.minutes) 
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :user_is_logged?, except: [:index,:show]

  # GET /events
  # GET /events.json
  def index
    @events = Event.recent
    @old_events = Event.old
    @need_availability_action = false
    if user_signed_in? 
      @availabilities = []

      @events.each do |evt|
        av = current_user.participate(evt) 
        if av.nil?
          av = Participating.new
          av.available = false
          @need_availability_action = true
        end
        @availabilities[evt.id] = av
      end
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
    @event.tier = 1
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :start_time,:tier, :meet_time, :players_required, user_ids: [], roles_attributes: [:id, :required_players, :role_type_id, :comment])
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_availabilities.html.erb
<% if user_signed_in? %>
    <div class="panel-footer form-inputs clearfix">
    	<% if availability.new_record? %>
    		<i class="fa fa-question-circle color-darkred"></i> 
            <% availability.available = 2 %>   	
    	<% else %>
    		<i class="fa fa-check color-darkgreen"></i>
		<% end %>
    	<%= simple_fields_for("participatings[]", availability , index: availability.object_id, html: {class: "form-inline "}) do |f| %>
      		<div class="pull-right"><%= f.input :available, label: "Disponible ?", as: :select, collection: {"Absent" => 0, "Présent" => 1, "Pas sûre" => 2}, include_blank: false %></div>
		    <%= f.input :id, as: :hidden %>
		    <%= f.input :role_id, collection: event.roles, label_method: :name, value_method: :id, :include_blank => false, label: "Role" %>
		    <%= f.input :character_id, collection: current_user.characters, label_method: :name, value_method: :id, :include_blank => false, label: "Personnage"%>
		    <%= f.input :comment, label: "Commentaire", :input_html => {:size => 50 }%>
    </div>
  <% end %>
<% end %>

app/views/events/_force_invite.html.erb
<% if user_signed_in? and current_user.lead?(event) %>
    <li class="list-group-item form-inputs clearfix">
<% pp = Participating.new %>
<% pp.available = 1 %>    
<%= simple_form_for(pp, html: {class: "form-inline "}) do |f| %>
      <%= f.error_notification %>

      <div class="badge" data-classe="Force">Force</div> &nbsp;
      <div class="pull-right">
        <%= f.input :available, label: "Disponible ?", as: :select, collection: {"Absent" => 0, "Présent" => 1, "Pas sûre" => 2} , include_blank: false%>
        <%= f.button :submit, "Inscrire"%>
        
      </div>
      <%= f.input :role_id, collection: event.roles, label_method: :name, value_method: :id, :include_blank => false, label: "Role" %>
      <%= f.input :character_id, collection: Character.all, label_method: :friendly_name, value_method: :id, :include_blank => false, label: "Personnage"%>
      <%= f.input :comment, label: "Commentaire" %>

    </li>

  <% end %>
<% end %>

app/views/events/_form.html.erb
<%= simple_form_for(@event, html: {class: 'form-horizontal'}) do |f| %>
<%= f.error_notification %>
<% 2.times {@event.roles.build} if @event.new_record?%>
<% 2.times {@event.roles.build}%>
<% @event.players_required = 20 %>

      <div class="well well-sm">
  <%= f.input :name, label: "Nom" %>
  <%= f.input :start_time, label: "Debute" %>
  <%= f.input :players_required, collection: 2..60, label: "Nombre de joueurs requis" %>
  <%= f.input :tier, label: "Palier", collection: 0..10 %>
  <%= f.input :description, label: "Description", :input_html => {:size => "60x5"} %>
  <%= f.association :users, collection: User.all.order("username"), label_method: :username, value_method: :id, input_html:{class: "raid_leads_tags_ids", style: "width: 400px;", data: {placeholder: "Entrer un(des) raid leads"} } , label: "Raid Leader"%>
    </div>
  <%= f.simple_fields_for :roles do |role| %>
      <div class="well well-sm">
        <%= role.input :required_players , label: "Nombre de joueurs requis"%>
        <%= role.association :role_type, label: "Role"%>
        <%= role.input :comment, :input_html => {:size => "30x3"}, label: "Commentaire" %>
      </div>
  <% end %>
  <%= f.submit @event.new_record? ? "Créer un évènement" : "Modifier l'évènement" , class: "btn btn-default btn-md"%>
<% end %>

app/views/events/_participation.html.erb
<% if  user_signed_in? and not current_user.participate?(event) and event.subscription_opened?  %>

    <li class="list-group-item form-inputs clearfix">
      <% pp = Participating.new %>
      <% pp.available = 2 %>
      <% pp.character = current_user.characters.first %>
      <% pp.role = event.roles.first %>
      <% pp.comment = "" %>

    <%= simple_form_for(pp, html: {class: "form-inline "}) do |f| %>
      <%= f.error_notification %>

      <div class="pull-right">
        <%= f.button :submit, "Valider", "data-classe"=>"ValidDispo" %>
        
      </div>
      <%= f.input :role_id, collection: event.roles, label_method: :name, value_method: :id, :include_blank => false, label: "Role" %>
      <%= f.input :character_id, collection: current_user.characters, label_method: :name, value_method: :id, :include_blank => false, label: "Personnage"%>
      <%= f.input :comment, label: "Commentaire" %>
      <%= f.input :available, label: "Disponible ?", as: :select, collection: {"Absent" => 0, "Présent" => 1, "Pas sûre" => 2}, include_blank: false %>

      <% end %>
    </li>
<% elsif not event.subscription_opened? %>
  <div class="panel-footer alert-danger">
        <i class="fa fa-gavel color-darkred"></i>  <small class=""> Inscriptions fermées !</small>
  </div>
<% end %>

app/views/events/_pickup.html.erb
<% if  user_signed_in? and current_user.lead?(event) %>
  <% pickup = Pickup.new %>
  <% pickup.build_participating %>
  <% pickup.participating.available = 1 %>
  <%= simple_form_for(pickup, html: {class: "form-inline "}) do |f| %>
    <%= f.error_notification %>

    <li class="list-group-item form-inputs clearfix">

      <div class="pull-right">
        <%= f.button :submit, "Ajoute pickup" %>
      </div>

      <div class="pull-left">
        <span class="badge" data-classe="Pickup">Pickup</span>&nbsp;
        <%= f.input :classe, label: "Classe", collection: Character.classes , :include_blank => false%>
        <%= f.input :name, labal: "Nom"%>
        <%= f.simple_fields_for :participating do |p| %>
          <%= p.input :role_id, collection: event.roles, label_method: :name, value_method: :id, :include_blank => false, label: "Role" %>
          <%= p.input :comment, label: "Commentaire" %>
          <%= p.input :available, as: :hidden %>
        <%end%>
        </div>
    </li>

  <%end%>
<%end%>

app/views/events/edit.html.erb
<h1>Modifier Evènement</h1>

<%= render 'form' %>


<br/>
<%= link_to 'Supprimer', @event, method: :delete, data: { confirm: 'Etes vous sure ?' }, class: "btn btn-default btn-md" %>

app/views/events/index.html.erb
<h1>Prochains évènements</h1>

    <%if user_signed_in? and current_user.characters.count == 0 %>
      <p class="alert alert-danger"><span style="background-color:darkred" title="Pas de personnages créé !" class="badge ">!</span>&nbsp;Vous devez avoir au moins un personnage pour pouvoir participer aux évènements !&nbsp;<a href="<%= new_character_path%>">&nbsp;Créez votre personnage</a>
      </p>
    <%end%>


    <% if @events.count > 0 %>
      <%= form_tag participating_create_or_update_path, class: "form-inline disponibilites" do %>
        <div class="clearfix">
          <% if user_signed_in? %>
            <div class="pull-right">
              <%= submit_tag "Valider Mes Disponibilitées", class: "btn btn-default btn-md", "data-classe"=>"ValidDispo" %>
              
            </div>
            <a href="<%= new_event_path%>" class="btn btn-default btn-md" ><i class="fa fa-plus"></i>&nbsp;Nouvel Evènement</a>
            <br/><br/>
              <%if @need_availability_action %>
              <div class="alert alert-danger width-100">
                <div class="">
                  <i class="fa fa-exclamation-circle color-darkred"></i>  <small class=""> Vous avez des disponibilitées non-renseignées, pensez à les valider. </small>
                </div>
              </div>
              <% end %>


          <% end %>
        </div>
        <% @events.each do |event| %>
          <div class="panel panel-default">            
              <div class="event-header panel-heading clearfix ">
                  <div class="pull-left">
                    <a href="<%= event_path(event)%>"><h3 class="panel-title"><%= event.name %></h3></a>
                    <small>
                      <i class="glyphicon glyphicon-time"></i>&nbsp;<%= l event.start_time, :format => :short %>
                    </small>
                  </div>
                  <div class="pull-right">
                    <span class="badge "><%= event.actual_players%>&nbsp;<i class="fa fa-user"></i></span> / <span class="badge "><%= event.players_required %>&nbsp;<i class="fa fa-users"></i></span><br/>
                    <span class="badge palier-<%= event.tier || 1 %>">
                      <i class="fa fa-bar-chart-o"></i>&nbsp;Palier <%= event.tier || 1 %>
                    </span>
                  </div>
              </div>
            <% unless event.description.empty? %>
            <div class="panel-body">
              <%= markdown(truncate(event.description, length: 200)) %>
            </div>
            <% end %>
            <% if event.subscription_opened? %>
              <%= render "availabilities", event: event, availability: @availabilities[event.id]  if user_signed_in? %>
            <% else %>
              <div class="panel-footer alert-danger">
                    <i class="fa fa-gavel color-darkred"></i>  <small class=""> Inscriptions fermées !</small>
              </div>
            <% end %>
          </div>
        <% end %>

        <% if user_signed_in? %>
            <div class="pull-right">
              <%= submit_tag "Valider Mes Disponibilitées", class: "btn btn-default btn-md", "data-classe"=>"ValidDispo" %>
              
            </div>
            <a href="<%= new_event_path%>" class="btn btn-default btn-md" ><i class="fa fa-plus"></i>&nbsp;Nouvel Evènement</a>
            <br/><br/>
              <%if @need_availability_action %>
              <div class="alert alert-danger width-100">
                <div class="">
                  <i class="fa fa-exclamation-circle color-darkred"></i>  <small class=""> Vous avez des disponibilitées non-renseignées, pensez à les valider. </small>
                </div>
              </div>
              <% end %>


          <% end %>

      <% end %>
    <% else %>
      <a href="<%= new_event_path%>" class="btn btn-default btn-md" ><i class="fa fa-plus"></i>&nbsp;Nouvel Evènement</a>
    <% end %>

<br>

<h2>Evènements récemment conclu</h2>

<% @old_events.each do |event| %>

      <div class="panel panel-default">

            
        <div class="event-header panel-heading clearfix">
            <div class="pull-left">
              <a href="<%= event_path(event)%>"><h3 class="panel-title"><%= event.name %></h3></a>
              <small><i class="glyphicon glyphicon-time"></i>&nbsp;<%= l event.start_time, :format => :short %></small>
            </div>
            <div class="pull-right">
              <span class="badge "><%= event.actual_players%>&nbsp;<i class="fa fa-user"></i></span> / 
              <span class="badge "><%= event.players_required %>&nbsp;<i class="fa fa-users"></i></span><br/>
                <span class="badge palier-<%= event.tier || 1 %>">
                  <i class="fa fa-bar-chart-o"></i>&nbsp;Palier <%= event.tier || 1 %>
                </span>
            </div>
        </div>
        <% unless event.description.empty? %>
        <div class="panel-body">
          <%= event.description %>
        </div>
        <%end%>
      </div>

<% end %>

app/views/events/new.html.erb
<h1>Nouvel Evènement</h1>

<%= render 'form' %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-heading clearfix event-header">
      <div class="pull-right text-right">
        <span class="badge "><%= @event.actual_players%>&nbsp;<i class="fa fa-user"></i></span> / <span class="badge "><%= @event.players_required %>&nbsp;<i class="fa fa-users"></i></span><br/>
        <span class="badge palier-<%= @event.tier || 1 %>"><i class="fa fa-bar-chart-o"></i>&nbsp;Palier <%= @event.tier || 1 %></span>&nbsp; 
        <% @event.users.each do |user|%><span class="badge leaders"><i class="fa fa-star"></i>&nbsp;&nbsp;<%=user.username%></span>&nbsp;<%end%>
      </div>

      <div >
        <h3 class="panel-title"><%= @event.name%></h3>
        <small>
          <i class="glyphicon glyphicon-time"></i>&nbsp;<%= l @event.start_time, :format => :short %>
        </small>    
      </div>
  </div>
  <% unless @event.description.empty? %>
  <div class="panel-body">
    <%= markdown(@event.description) %>
  </div>
  <%end%>
    <ul class="list-group">
      <%= render "participation", :event => @event %>
      <%= render "pickup", :event => @event %>
      <%= render "force_invite", :event => @event %>
    </ul>
        

  <div class="panel-group" id="accordion">
  <% @event.roles.each do |role| %>
      <div class="panel panel-default">
        <div class="panel-heading event-subheader clearfix" data-classe="RoleBesoin">
          <div class="pull-right">
            <small><span class="badge "><%= role.actual_players_count%>&nbsp;<i class="fa fa-user"></i></span> 
            / <span class="badge "><%= role.required_players %>&nbsp;<i class="fa fa-users"></i></span></small>
          </div>
          <h5><%=role.name%></h5>
        </div>
        
          <% unless role.comment.empty? %>
        <div class="panel-body">
            <%= role.comment %>
        </div>
          <% end %>
        <ul class="list-group">
 
          <% role.participating.each do |pp| %>
               <li class="list-group-item">
                  <div class="clearfix" <% unless pp.available? %>data-classe="ListIndispo"<%end%> >
                    <h4 data-toggle="collapse" data-parent="#accordion" href="#collapse<%=pp.id%>" class="clearfix panel-title">
                      <div class="pull-right">
                        <%= link_to raw("<i  style=\"color:darkred\"  class=\"fa fa-times-circle\"></i>"), pp, method: :delete if user_signed_in? and (current_user.lead?(@event) or (pp.pickup.nil? and pp.character.user == current_user))%>&nbsp;&nbsp;<i class="fa fa-caret-square-o-down"></i>
                      </div>
                      <%= pp.name %>&nbsp;                      
                      <span class="badge" data-classe="<%= pp.classe %>"><%= pp.classe %></span>&nbsp;
                      <% if pp.is_pickup? %><span class="badge" data-classe="Pickup">Pickup</span>&nbsp;<%end%>
                      <% if pp.away? %><span class="badge" data-classe="Indisponible">Indisponible</span>&nbsp;<%end%>
                      <% if pp.unsure? %><span class="badge" data-classe="Indisponible">Pas sûre</span>&nbsp;<%end%>
                      <% unless pp.character.nil? or pp.character.comment.nil? or pp.character.comment.empty? %><small><i class="fa fa-comment"></i>&nbsp;&nbsp;<%= pp.character.comment %></small><%end%>
                      <% unless pp.comment.nil? or pp.comment.empty? %><small><i class="fa fa-comment"></i>&nbsp;&nbsp;<%= pp.comment %></small><%end%>
                      
                    </h4>
                </div>
                <% if pp.pickup.nil? %>
                  <div id="collapse<%=pp.id%>" class="collapse out">
                    <div class="panel-body">
                      <i class="fa fa-beer"></i>&nbsp;<% pp.character.character_specialisations.each do |cs| %><span class="badge"><%= cs.role_type.name %>&nbsp;:&nbsp;<small><%= cs.comment%></small></span>&nbsp;<%end%>
                    </div>
                  </div>
                <% end %>
            </li>
          <% end %>
          </ul>
      </div>
  <% end %> 
  </div>
</div>

<%= link_to 'Modifier', edit_event_path(@event) , class: "btn btn-default btn-md" if user_signed_in? and current_user.lead?(@event)%>