config/routes.rb
Rails.application.routes.draw do
  get 'availabilities/show', as: :show_availabilities

  get 'availabilities/update', as: :update_availabilities

  resources :participatings
  post "participatings/create_or_update" => 'participatings#create_or_update', as: :participating_create_or_update

  resources :leaders

  resources :announcements

  resources :character_specialisations

  resources :characters

  resources :pickups

  resources :requireds

  resources :roles

  resources :event_templates

  resources :events

  resources :role_types

  get 'guild/index'

  get 'guild/about', as: :about

  put 'guild/promote_user/:uid' => 'guild#promote_user' , as: :user_promote_admin
  put 'guild/demote_user/:uid'  => 'guild#demote_user', as: :user_demote_admin
  put 'guild/make_pickup/:uid' => 'guild#make_pickup', as: :user_make_pickup
  put 'guild/make_guildmate/:uid' => 'guild#make_guildmate', as: :user_make_guildmate

  delete 'guild/remove_user/:uid'  => 'guild#remove_user', as: :user_delete

  devise_for :users

  root 'guild#index'

end

app/models/character.rb
class Character < ActiveRecord::Base
	has_many :participating, dependent: :destroy
	has_many :roles, through: :participating
	has_many :character_specialisations, dependent: :destroy
	has_many :role_types, through: :character_specialisations
	accepts_nested_attributes_for :character_specialisations, :reject_if => lambda { |a| a[:role_type_id].blank?}
	belongs_to :user

	def self.classes
		["Guerrier", "Mage", "Voleur", "Clerc", "Primaliste"]		
	end

	def friendly_name
		"[#{user.username}] #{name}"
	end

	
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]
  before_action :user_is_logged?

  # GET /characters/new
  def new
    @character = current_user.characters.build
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = current_user.characters.build(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to edit_user_registration_path, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to edit_user_registration_path, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to edit_user_registration_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:user_id, :ordered, :classe, :name, :comment, character_specialisations_attributes: [:id, :role_type_id, :comment])
    end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= simple_form_for(@character, html: {class: "form-inline"} ) do |f| %>
  <%= f.error_notification %>
<% 2.times {@character.character_specialisations.build} if @character.new_record?%>
<% 2.times {@character.character_specialisations.build}%>
    <div class="well well-sm">
      <%= f.input :name, label: "Nom" %>
      <%= f.input :classe, label: "Classe", collection: Character.classes %>
      <%= f.input :comment, label: "Commentaire" %>
    </div>

        <%= f.simple_fields_for :character_specialisations do |ff| %>
      <div class="well well-sm">
          <%= ff.association :role_type %>
          <%= ff.input :comment, label: "Commentaire" %>
      </div>    
        <% end %>
  <%= f.submit @character.new_record? ? "Créer le Personage" : "Modifier le Personage" , class: "btn btn-default btn-md"%>
<% end %>

   <!--  when 1
      "Guerrier"
    when 2
      "Mage"
    when 3
      "Voleur"
    when 4
      "Clerc"
    end -->

app/views/characters/edit.html.erb
<h1>Modifier le personnage</h1>

<%= render 'form' %>

app/views/characters/index.html.erb
<h1>Listing characters</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Ordered</th>
      <th>Class</th>
      <th>Name</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= character.user_id %></td>
        <td><%= character.ordered %></td>
        <td><%= character.class_id %></td>
        <td><%= character.name %></td>
        <td><%= character.comment %></td>
        <td><%= link_to 'Show', character %></td>
        <td><%= link_to 'Edit', edit_character_path(character) %></td>
        <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>Nouveau Personnage</h1>

<%= render 'form' %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @character.user_id %>
</p>

<p>
  <strong>Ordered:</strong>
  <%= @character.ordered %>
</p>

<p>
  <strong>Class:</strong>
  <%= @character.classe %>
</p>

<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @character.comment %>
</p>

<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>